Factory/Models/DesignTimeDbContext.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Configuration;
using System.IO;

namespace Factory.Models
{
  public class FactoryContextFactory : IDesignTimeDbContextFactory<FactoryContext>
  {

    FactoryContext IDesignTimeDbContextFactory<FactoryContext>.CreateDbContext(string[] args)
    {
      IConfigurationRoot configuration = new ConfigurationBuilder()
        .SetBasePath(Directory.GetCurrentDirectory())
        .AddJsonFile("appsettings.json")
        .Build();

      var builder = new DbContextOptionsBuilder<FactoryContext>();

      builder.UseMySql(configuration["ConnectionStrings:DefaultConnection"], ServerVersion.AutoDetect(configuration["ConnectionStrings:DefaultConnection"]));

      return new FactoryContext(builder.Options);
    }
  }
}

Factory/Models/DesignTimeDbContextFactory.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Configuration;
using System.IO;

namespace Factory.Models
{
  public class FactoryContextFactory : IDesignTimeDbContextFactory<FactoryContext>
  {
    FactoryContext IDesignTimeDbContextFactory<FactoryContext>.CreateDbContext(string[] args)
    {
      IConfigurationRoot configuration = new ConfigurationBuilder()
          .SetBasePath(Directory.GetCurrentDirectory())
          .AddJsonFile("appsettings.json")
          .Build();

      var builder = new DbContextOptionsBuilder<FactoryContext>();

      builder.UseMySql(configuration["ConnectionStrings:DefaultConnection"], ServerVersion.AutoDetect(configuration["ConnectionStrings:DefaultConnection"]));

      return new FactoryContext(builder.Options);
    }
  }
}

Factory/Models/Engineer.cs
using System.Collections.Generic;

namespace Factory.Models
{
  public class Engineer
  {
    public Engineer()
    {
      this.JoinEntities = new HashSet<MachineEngineer>();
    }

    public int EngineerId { get; set; }
    public string EngineerName { get; set; }
    public string EngineerStatus { get; set; }
    public virtual ICollection<MachineEngineer> JoinEntities { get; set; }
  }
}

Factory/Models/FactoryContext.cs
using Microsoft.EntityFrameworkCore;

namespace Factory.Models
{
  public class FactoryContext : DbContext
  {
    public DbSet<Engineer> Engineers { get; set; }
    public DbSet<Machine> Machines { get; set; }
    public DbSet<MachineEngineer> MachineEngineer { get; set; }

    public FactoryContext(DbContextOptions options) : base(options) { }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      optionsBuilder.UseLazyLoadingProxies();
    }
  }
}

Factory/Models/Machine.cs
using System.Collections.Generic;

namespace Factory.Models
{
  public class Machine
  {
    public Machine()
    {
      this.JoinEntities = new HashSet<MachineEngineer>();
    }

    public int MachineId { get; set; }
    public string MachineType { get; set; } 
    public string MachineStatus { get; set; }
    public virtual ICollection<MachineEngineer> JoinEntities { get; set; }
  }
}

Factory/Models/MachineEngineer.cs
using System.Collections.Generic;

namespace Factory.Models
{
  public class MachineEngineer
  {
    public int MachineEngineerId { get; set; }
    public int EngineerId { get; set; }
    public int MachineId { get; set; }
    public virtual Engineer Engineer { get; set; }
    public virtual Machine Machine { get; set; }
  }
}

Factory/Controllers/EngineersController.cs
using Factory.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace Factory.Controllers
{
  public class EngineersController : Controller
  {
    private readonly FactoryContext _db;

    public EngineersController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Engineers.ToList());
    }

    public ActionResult Create()
    {
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "MachineType");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Engineer engineer, int MachineId)
    {
      _db.Engineers.Add(engineer);
      _db.SaveChanges();
      if (MachineId != 0)
      {
        _db.MachineEngineer.Add(new MachineEngineer() { MachineId = MachineId, EngineerId = engineer.EngineerId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisEngineer = _db.Engineers
        .Include(engineer => engineer.JoinEntities)
        .ThenInclude(join => join.Engineer)
        .FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    public ActionResult Edit(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "MachineType");
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult Edit(Engineer engineer, int MachineId)
    {
      if (MachineId != 0)
      {
        _db.MachineEngineer.Add(new MachineEngineer() { MachineId = MachineId, EngineerId = engineer.EngineerId });
      }
      _db.Entry(engineer).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddMachine(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "MachineType");
      return View(thisEngineer);
    }

    [HttpPost]
    public ActionResult AddMachine(Engineer engineer, int MachineId)
    {
      if (MachineId != 0)
      {
        _db.MachineEngineer.Add(new MachineEngineer() { MachineId = MachineId, EngineerId = engineer.EngineerId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      _db.Engineers.Remove(thisEngineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteMachine(int joinId)
    {
      var joinEntry = _db.MachineEngineer.FirstOrDefault(entry => entry.MachineEngineerId == joinId);
      _db.MachineEngineer.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Factory/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Factory.Controllers
{
    public class HomeController : Controller
    {

      [HttpGet("/")]
      public ActionResult Index()
      {
        return View();
      }

    }
}

Factory/Controllers/MachinesController.cs
using Factory.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace Factory.Controllers
{
  public class MachinesController : Controller
  {
    private readonly FactoryContext _db;

    public MachinesController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Machine> model = _db.Machines.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Machine machine)
    {
      _db.Machines.Add(machine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisMachine = _db.Machines
        .Include(machine => machine.JoinEntities)
        .ThenInclude(join => join.Engineer)
        .FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    public ActionResult Edit(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult Edit(Machine machine)
    {
      _db.Entry(machine).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      _db.Machines.Remove(thisMachine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Factory/Views/Engineers/AddMachine.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h3>Add a Machine to this Category: @Html.DisplayFor(model => model.EngineerName)</h3>
<hr>

@using (Html.BeginForm())
{
  <div class="form-group">
    @Html.HiddenFor(model => model.EngineerId)

    <h5>@Html.Label("Select Machine")</h5>
    @Html.DropDownList("MachineId", null, new { @class = "form-control" })
    <br>

    <input type="submit" value="Save" class = "btn btn-dark"/>
  </div>
}

<p class="btn btn-dark">@Html.ActionLink("Back to Engineers", "Index", null, null, new { @class = "text"})</p>
<p class="btn btn-dark">@Html.ActionLink("Add a New Machine", "Create", "Machines", "Create", new { @class = "text"})</p>

Factory/Views/Engineers/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h3>Add Engineer/Machine Group</h3>
<hr>

@using (Html.BeginForm())
{
  <div class="form-group">
    <h5>Engineer Name</h5>
    @Html.TextBoxFor(model => model.EngineerName, new { @class = "form-control", @required = "required"})
    <br>
    <h5>Engineer @Html.LabelFor(model => model.EngineerStatus)</h5>
    @Html.ListBox("EngineerStatus", new List<SelectListItem> { 
      new SelectListItem { Text = "On Duty", Value = "On Duty"},
      new SelectListItem { Text = "Ready", Value = "Ready"},
      new SelectListItem { Text = "Break", Value = "Break"}
      }, new { @class = "form-control"})
      <br>
        <h5>Machine Type:</h5>
        @Html.DropDownList("MachineId", null, new { @class = "form-control" })
      <br>
    <input type="submit" value="Add New Engineer" class="btn btn-dark text"/>
  </div>
}

<br>
<p class="btn btn-dark">@Html.ActionLink("Show All Engineers", "Index", null, null, new { @class = "text" })</p>
<p class="btn btn-dark">@Html.ActionLink("See All Machines", "Index", "Machines", null, new { @class = "text" })</p>

Factory/Views/Engineers/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h4>Confirm Delete?</h4>
<br>

<h4>Engineer Name: @Html.DisplayFor(model => model.EngineerName)</h4>

@using (Html.BeginForm())
{
  <br> 
  <input type="submit" value="Delete" class="btn btn-dark text"/>
}

<br>
<p class="btn btn-dark">@Html.ActionLink("Back to List", "Index", null, null, new { @class = "text" })</p>

Factory/Views/Engineers/Details.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h3>Engineer Details: @Html.DisplayFor(model => model.EngineerName)</h3>
<hr>

<h5>Engineer Status: @Html.DisplayFor(model => model.EngineerStatus)</h5>

<br>
@if (@Model.JoinEntities.Count == 0)
{
  <p>This engineer does not have any machines.</p>
}
else 
{
  <h4>Machines this Engineer is working on:</h4>
  <br>

  @foreach(var join in @Model.JoinEntities)
  {
  <div class="card-deck">
    <div class="card text-center border-light mb-3" style="width: 22rem;">
      <div class="card-body">
        <h4 class="card-title">@join.Machine.MachineType</h4>
            @using (Html.BeginForm("DeleteMachine", "Engineers"))
            {
              @Html.Hidden("joinId", @join.MachineEngineerId)
              <input type="submit" value="Delete" class = "btn btn-dark text"/>
            }
          <div class="card-footer text-muted">
            <p>Machine Status: @join.Machine.MachineStatus</p>
          </div>
      </div>
    </div>
  </div>
  }
}

<p class="btn btn-dark">@Html.ActionLink("Add a Machine", "AddMachine", new { id = Model.EngineerId }, new { @class = "text" })</p>
<p class="btn btn-dark">@Html.ActionLink("Back to List", "Index", null, null, new { @class = "text" })</p>
<p class="btn btn-dark">@Html.ActionLink("Edit Engineer", "Edit", new { id = Model.EngineerId }, new { @class = "text" })</p>
<p class="btn btn-dark">@Html.ActionLink("Delete Engineer", "Delete", new { id = Model.EngineerId }, new { @class = "text" })</p>

Factory/Views/Engineers/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h3>Edit Engineer Details: @Html.DisplayFor(model => model.EngineerName)</h3>
<hr>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.EngineerId)
  <div class="form-group">
    <h4>Engineer Name:</h4>
    @Html.EditorFor(model => model.EngineerName, new { htmlAttributes = new { @class = "form-control" }})
  </div>
  <div class="form-group">
    <h4>@Html.Label("Select Machine")</h4>
    @Html.DropDownList("MachineId", null, new { @class = "form-control" })
  </div>
  
  <input type="submit" value="Save" class = "btn btn-dark text"/>
}

<p class="btn btn-dark">@Html.ActionLink("Back to List", "Index", null, null, new { @class = "text" })</p>

Factory/Views/Engineers/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;
@model List<Factory.Models.Engineer>;

<h3>Engineers</h3>
<hr>

@if (@Model.Count == 0)
{
  <h4>There are no Engineers Added.</h4>
}

@foreach (Engineer engineer in Model)
{
  <div class="card-deck">
    <div class="card text-center mb-3" style="width: 22rem;">
      <div class="card-body">
        <h5 class="card-title">@Html.ActionLink($"{engineer.EngineerName}", "Details", new { id = engineer.EngineerId }, new { @class = "text" })</h5>
        <p class="card-text">@engineer.EngineerStatus</p>
      </div>
    </div>
  </div>
}

<p class="btn btn-dark">@Html.ActionLink("Add New Engineer", "Create", null, null, new { @class = "text" })<p>
<p class="btn btn-dark">@Html.ActionLink("Add a Machine", "AddMachine", null, null, new { @class = "text" })<p>
<p class="btn btn-dark">@Html.ActionLink("Return Home", "Index", "Home", null, new { @class = "text" })<p>

Factory/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<span>Dr.Sillystringz's Factory Database Management System</span> 

<br>

<p class="btn btn-dark btn-lg btn-block">@Html.ActionLink("See All Machines", "Index", "Machines", null, new { @class = "text" })</p>
<p class="btn btn-dark btn-lg btn-block">@Html.ActionLink("See All Engineers", "Index", "Engineers", null, new { @class = "text" })</p>

Factory/Views/Machines/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h3>Add Machine</h3>
<hr>

@using (Html.BeginForm())
{
  <div class="form-group">
    <h5>Machine Type:</h5>
    @Html.TextBoxFor(model => model.MachineType, new { @class = "form-control", @required = "required" })
    <br>
    
    <h5>Machine Status</h5>
    @Html.ListBox("MachineStatus", new List<SelectListItem> { 
      new SelectListItem { Text = "Working", Value = "Working"},
      new SelectListItem { Text = "Out of Order", Value = "Out of Order"},
      new SelectListItem { Text = "Repair", Value = "Repair"}
      }, new { @class = "form-control"})
      <br>

    <input type="submit" value="Add New Machine" class="btn btn-dark text"/>
  </div>
}

<br>
<p class="btn btn-dark">@Html.ActionLink("See All Machines", "Index", null, null, new { @class = "text" })</p>

Factory/Views/Machines/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h4>Confirm Delete?</h4>

<br>
<h4>Machine Name: @Html.DisplayFor(model => model.MachineType)</h4>

@using (Html.BeginForm())
{
  <br>
  <input type="submit" value="Delete" class="btn btn-dark text"/>
}

<br>
<p class="btn btn-dark">@Html.ActionLink("Back to Machines", "Index", null, null, new { @class = "text" })</p>

Factory/Views/Machines/Details.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h3>Machine Details</h3>
<hr>

<h4>Machine Type: @Html.DisplayFor(model => model.MachineType)</h4>

@if (@Model.JoinEntities.Count == 0)
{
  <p>This machine has no engineer assigned.</p>
}
else
{
  <h4>Engineers assinged to this machine:</h4>
  <ul>
    @foreach(var join in Model.JoinEntities)
    {
      <h5>@join.Engineer.EngineerName</h5>
    }
  </ul>
}

<p class="btn btn-dark">@Html.ActionLink("Back to Machines", "Index", null, null, new { @class = "text" })</p>
<p class="btn btn-dark">@Html.ActionLink("Edit Machine", "Edit", new { id = Model.MachineId}, new { @class = "text" })</p>
<p class="btn btn-dark">@Html.ActionLink("Delete Machine", "Delete", new { id = Model.MachineId}, new { @class = "text" })</p>
<p class="btn btn-dark">@Html.ActionLink("Back to Engineers", "Index", "Engineers", null, new { @class = "text" })</p>

Factory/Views/Machines/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h3>Edit Machine Details: @Html.DisplayFor(model => model.MachineType)</h3>
<hr>

@using (Html.BeginForm())
{
  <div class="form-group">
    @Html.HiddenFor(model => model.MachineId)

    <h4>Machine Type:</h4>
    @Html.EditorFor(model => model.MachineType, new { htmlAttributes = new { @class = "form-control" } })
    <br>

    <input type="submit" value="Save" class = "btn btn-dark text"/>
  </div>
}

<br>
<p class="btn btn-dark">@Html.ActionLink("Back to List", "Index", null, null, new { @class = "text" })</p>

Factory/Views/Machines/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;

<h3>Machines</h3>
<hr>

@if (@Model.Count == 0)
{
  <h4>There are no machines added.</h4>
}
@foreach (Machine machine in Model)
{
  <div class="card-deck">
    <div class="card text-center mb-3" style="width: 22rem;">
      <div class="card-body">
        <h5 class="card-title">@Html.ActionLink($"{machine.MachineType}", "Details", new { id = machine.MachineId }, new { @class = "text" })</h5>
          <p class="card-text">@machine.MachineStatus</p>
      </div>
    </div>
  </div>
}
<br>
<p class="btn btn-dark">@Html.ActionLink("Add New Machine", "Create", null, null, new { @class = "text" })</p>
<p class="btn btn-dark">@Html.ActionLink("Return Home", "Index", "Home", null, new { @class = "text" })<p>

Factory/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Sillystringz Factory</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/styles.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Zilla+Slab:wght@300&display=swap" rel="stylesheet">
  </head>
  <body>
    <div class="container">
      @RenderBody()
    </div>
  </body>
</html>